/*
 * This file is generated by jOOQ.
 */
package com.petclinic;


import com.petclinic.tables.Owners;
import com.petclinic.tables.Pets;
import com.petclinic.tables.Specialties;
import com.petclinic.tables.Types;
import com.petclinic.tables.Vets;
import com.petclinic.tables.Visits;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OWNERS_LAST_NAME_IDX = Internal.createIndex(DSL.name("owners_last_name_idx"), Owners.OWNERS, new OrderField[] { Owners.OWNERS.LAST_NAME }, false);
    public static final Index PETS_NAME_IDX = Internal.createIndex(DSL.name("pets_name_idx"), Pets.PETS, new OrderField[] { Pets.PETS.NAME }, false);
    public static final Index PETS_OWNER_ID_IDX = Internal.createIndex(DSL.name("pets_owner_id_idx"), Pets.PETS, new OrderField[] { Pets.PETS.OWNER_ID }, false);
    public static final Index SPECIALTIES_NAME_IDX = Internal.createIndex(DSL.name("specialties_name_idx"), Specialties.SPECIALTIES, new OrderField[] { Specialties.SPECIALTIES.NAME }, false);
    public static final Index TYPES_NAME_IDX = Internal.createIndex(DSL.name("types_name_idx"), Types.TYPES, new OrderField[] { Types.TYPES.NAME }, false);
    public static final Index VETS_LAST_NAME_IDX = Internal.createIndex(DSL.name("vets_last_name_idx"), Vets.VETS, new OrderField[] { Vets.VETS.LAST_NAME }, false);
    public static final Index VISITS_PET_ID_IDX = Internal.createIndex(DSL.name("visits_pet_id_idx"), Visits.VISITS, new OrderField[] { Visits.VISITS.PET_ID }, false);
}
