/*
 * This file is generated by jOOQ.
 */
package com.petclinic;


import com.petclinic.tables.Owners;
import com.petclinic.tables.Pets;
import com.petclinic.tables.Specialties;
import com.petclinic.tables.Types;
import com.petclinic.tables.VetSpecialties;
import com.petclinic.tables.Vets;
import com.petclinic.tables.Visits;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.owners</code>.
     */
    public static final Owners OWNERS = Owners.OWNERS;

    /**
     * The table <code>public.pets</code>.
     */
    public static final Pets PETS = Pets.PETS;

    /**
     * The table <code>public.specialties</code>.
     */
    public static final Specialties SPECIALTIES = Specialties.SPECIALTIES;

    /**
     * The table <code>public.types</code>.
     */
    public static final Types TYPES = Types.TYPES;

    /**
     * The table <code>public.vet_specialties</code>.
     */
    public static final VetSpecialties VET_SPECIALTIES = VetSpecialties.VET_SPECIALTIES;

    /**
     * The table <code>public.vets</code>.
     */
    public static final Vets VETS = Vets.VETS;

    /**
     * The table <code>public.visits</code>.
     */
    public static final Visits VISITS = Visits.VISITS;
}
